### ISSUE TITLE
Teleportation while walking on bugs in a great fairy's fountain

### ISSUE THREAD

**Issue by TriRetr0** [Roman971/OoT-Randomizer#46]
# Video [here](https://cdn.discordapp.com/attachments/517421172691042334/776089644240470078/Nouveau_projet.mp4)

I don't know why it's happening but it doesn't work on a original rom.

(seed: [343PAM5YT0](https://cdn.discordapp.com/attachments/764557661466918922/776002371099820042/TriRetr0_OoT_57CA8_343PAM5YT0.zpf))

**Comment by Roman971** [comment]
@Fig02 I assume this isn't supposed to happen with the great fairy changes?

The version used was 5.2.119 R-1 according to the patch, so it should include the latest changes.

**Comment by Roman971** [comment]
Nevermind, it looks like the version used was 5.2.65 R-? (not sure which Dev-R version but it shouldn't matter). So that was before the recent changes and is probably fixed now, but it would probably be a good idea to confirm it.

I was mislead by a patching bug that overwrites the version, but thankfully I just looked at <https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1156> which mentions and fixes this very issue. Nice timing.

**Comment by TriRetr0** [comment]
It was generated with 5.2.117 R-1 but I patched with an older version (5.2.65 R-9 ?)

**Comment by Cuphat** [comment]
> It was generated with 5.2.117 R-1 but I patched with an older version (5.2.65 R-9 ?)

The version in the header of the patch file is definitely 5.2.65 which means that it was generated on that version.

Glad that catching the version number bug actually helped out some lmao.

**Comment by fig02** [comment]
hella late on this, but yeah this was fixed a while back
