### ISSUE TITLE
impossible seed with shadow temple entrance

### ISSUE THREAD

**Issue by Inversil** [Roman971/OoT-Randomizer#49]
Hey,
thanks for your amazing fork. 

we just finished playing a seed on it and we got stuck at the very end of the game because the ocarina was locked behind the shadow temple entrance at the graveyard, which you cannot access without a warp song. The other side of the LW forest bridge went into the carpenter's tent room, which you also cannot access from the other side.

I thought I would make a report of this logic inconsistency because it might be useful to you. Here is the spoiler log:

[OoT_4E414_XXAKBB0NZK_Spoiler.txt](https://github.com/Roman971/OoT-Randomizer/files/5736664/OoT_4E414_XXAKBB0NZK_Spoiler.txt)

**Comment by Roman971** [comment]
Hi, thanks.

In this seed it looks like you were expected to use the Longshot from Lost Woods to get on the bridge as adult, and then receive your ocarina from Saria. I could be wrong but that's what I understand from the log.

Being able to get on the bridge from the rest of lost woods isn't very well known since it's a scenario specific to randomized entrances, but it's pretty important when ocarinas aren't shuffled.
For your future seeds, I suggest looking at this page to get a list of similar quirks you can be expected to know when randomizing entrances: <https://wiki.ootrandomizer.com/index.php?title=Entrance_Randomizer#ER_Logic_Quirks>

**Comment by Inversil** [comment]
ah, I forgot to close this issue; that seems to be the answer! thank you! 

I had no idea that you could even do this; I thought there was an invisible wall above the bridge that extends out into the sky
