### ISSUE TITLE
Randomize Chu Salesman and Medigoron

### ISSUE THREAD

**Issue by RawZ06** [Roman971/OoT-Randomizer#5]
I proposed to add the possibility to randomize Chu Salesman and Medigoron.

### Randomize Chu Salesman

The saleman in the wasteland gives a random item and a 2nd pack with 20 chu is added on the pool_item. It's required ((epona and hover) or longshot) and first wallet.

### Randomize Medigoron 

Medigoron, who on vanilla give the Giant sword who can be broken, will be randomized.

It's required (strength or bomb or chu if chu is in logic or hammer) and wallet

I suggest two options : 

1. It's just a new check, and a blue rupee will be added, for example.

2. The Giant Sword is randomized, and it's progressive item with the Biggoron Sword. Two swords will be in the item pool, the first give the Giant Sword and the second Biggoron Sword.

**Comment by Roman971** [comment]
Nowadays this is actually being discussed for TR's fork but even if that doesn't happen I'll most likely add it in this fork myself soon.
It shouldn't be very complicated in theory but I'm still debating whether these belong in separate options or a common option.

**Comment by Roman971** [comment]
Version 5.1.63 R-7 (4b8641b231f6ffd832abb9b26b4cb2ce6c7ecb78) adds the option "Shuffle Medigoron & Carpet Salesman" which provides this possibility. I ended up going for a common option since I think that's what makes the most sense.

As suggested, when enabled, a pack of Bombchus and a Giant's Knife are added in the pool. Giant's Knife isn't progressive with Biggoron Sword but it also won't override the Sword when obtained after it, so their presence in the pool together shouldn't conflict in any way.
